---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: day2-as-sno-4
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/romerobu/workshop-gitops-content-deploy.git
      revision: sno-4-setup
      files:
      - path: "config-definition/**/config.json" 
  template:
    metadata:
      name: 'sno-4-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/romerobu/workshop-gitops-content-deploy.git
        targetRevision: sno-4-setup
        path: .
        helm:
          valueFiles:
            - '{{valuesFile}}'        
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: openshift-gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true 